### ISSUE TITLE
Email parse event error

### ISSUE THREAD

**Issue by smillerk2** [Jericho/StrongGrid#202] opened 2017-10-25 15:10 UTC
I'm getting this error when POSTing the [example default payload](https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html#-Example-Default-Payload)

```
[MultipartParseException]: Duplicate field in section
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize)
   at StrongGrid.WebhookParser.ParseInboundEmailWebhook(Stream stream) in C:\projects\stronggrid\Source\StrongGrid\WebhookParser.cs:line 61
```
I am using bash and reading the example into a variable and then POSTing:
```curl --header "Content-type: multipart/form-data" --request POST --data "$value" http://xxx.xxx/email```

**Comment by Jericho** [comment] 2017-10-25 15:28
Can you post your entire code to read the data into variable in order to allow me to reproduce?

Otherwise, my best guess is that something is malformed in the posted data, as evidenced by the fact that this exception occurs when we parse the posted multipart form data.

**Comment by smillerk2** [comment] 2017-10-25 15:30
I appreciate the quick response.
```
#!/bin/bash
value=`cat email-default.txt`
echo "$value"
curl --header "Content-type: multipart/form-data" --request POST --data "$value" "http://user:pass@test.com/Email"
```

**Comment by Jericho** [comment] 2017-10-25 15:34
ok, let me see if I can reproduce... (by the way, I'll be away from my desk for a few hours after lunch so I may not get back to you until late today or even tomorrow).

**Comment by smillerk2** [comment] 2017-10-25 15:37
No problem. I've tried both the default and raw examples as shown on https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html#-Example-Default-Payload and have also tested with/without:

```--header "Content-type: multipart/form-data"```

**Comment by Jericho** [comment] 2017-10-25 15:43
I confirm I can reproduce the issue with the "default" payload. The exception I get is: `Duplicate field in section`. I am now researching which "field" the exception is referring to...

**Comment by Jericho** [comment] 2017-10-25 15:55
The parser is choking because two lines begin with the same "field name" (in this case, the duplicate name is "received"):
```
Received: from mail-io0-f169.google.com (mail-io0-f169.google.com [209.85.223.169]) by mx0047p1mdw1.sendgrid.net (Postfix) with ESMTPS id AA9FFA817F2 for <parse@parse.yourdomain.com>; Wed, 27 Jul 2016 20:53:06 +0000 (UTC)
Received: by mail-io0-f169.google.com with SMTP id b62so81593819iod.3 for <parse@parse.yourdomain.com>; Wed, 27 Jul 2016 13:53:06 -0700 (PDT)
```

I will resume investigating later but at this point my guess is that it may be a problem with line termination or something like that.

**Comment by smillerk2** [comment] 2017-10-25 17:24
If I remove those "received" lines then I get further but there are other duplicates detected:

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sendgrid.com; s=ga1; h=mime-version:from:date:message-id:subject:to; bh=DpB1CYYeumytcPF3q0Upvx3Sq/oF4ZblEwnuVzFwqGI=; b=GH5YTxjt6r4HoTa+94w6ZGQszFQSgegF+Jlv69YV76OLycJI4Gxdwfh6Wlqfez5yID 5dsWuqaVJZQyMq/Dy/c2gHSqVo60BKG56YrynYeSrMPy8abE/6/muPilYxDoPoEyIr/c UXH5rhOKjmJ7nICKu1o99Tfl0cXyCskE7ERW0=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=1e100.net; s=20130820; h=x-gm-message-state:mime-version:from:date:message-id:subject:to; bh=DpB1CYYeumytcPF3q0Upvx3Sq/oF4ZblEwnuVzFwqGI=; b=Sq6LVHbmywBdt3sTBn19U8VOmelfoJltz8IcnvcETZsYwk96RBxN+RKMN5fOZSKw4j 15HrgdIFfyDmp67YK0ygvOITlTvZ6XY5I0PtnvDtAQt79kS3tKjI3QKJoEp/ZjIjSzlL KG7agl6cxFgBbIN0yHWBOvy3O+ZXY8tZdom1yOvULjmjW1U9JkdOs+aJ6zq4qhZX/RM/ tIgLB461eJ5V95iQDDc5Ibj9Cvy4vJfXLQRO0nLVQAT2Yz58tkEO1bDZpWOPAyUNneIL yhIWp+SpbuqhMA68mq0krG1PjmWalUbpVcGJIGuOKB9mQFFo/MqdrUCjvYnyo1jPLPeX psdQ==
```

Even though the names differ, the attributes contained within share the same names and this also causes it to fail.

**Comment by Jericho** [comment] 2017-10-26 13:34
Ok, two observations: 

1. the format in the sample payload provided by SendGrid is not what we expect. I put together the following myself sample: [EmailFromSendGrid.txt](https://github.com/Jericho/StrongGrid/files/1418517/EmailFromSendGrid.txt)
2. There is definitely an issue with line termination when the text file is read and/or posted by the "curl" command. I wrote a quick C# unit test to read the text file into a stream (this is meant to replace your bash script) and parse this stream. This works fine:

```csharp
[Fact]
public void Parse()
{
	// Arrange
	using (var stream = System.IO.File.OpenRead("emailfromSendGrid.txt"))
	{

		// Act
		var parser = new WebhookParser();
		var inboundEmail = parser.ParseInboundEmailWebhook(stream);

		// Assert
		inboundEmail.Subject.ShouldBe("Test #1");
	}
}
```

**Comment by smillerk2** [comment] 2017-10-26 14:03
I'm getting an index out of range exception with that test case using the file you have posted:

```
Test Name:	can_read_file
Test Outcome:	Failed
Test Duration:	0:00:00.1818488

Result StackTrace:	
at StrongGrid.WebhookParser.ParseEmailAddress(String rawEmailAddress) in C:\projects\stronggrid\Source\StrongGrid\WebhookParser.cs:line 158
   at StrongGrid.WebhookParser.<ParseEmailAddresses>b__3_0(String rawEmail) in C:\projects\stronggrid\Source\StrongGrid\WebhookParser.cs:line 152
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at StrongGrid.WebhookParser.ParseEmailAddresses(String rawEmailAddresses) in C:\projects\stronggrid\Source\StrongGrid\WebhookParser.cs:line 152
   at StrongGrid.WebhookParser.ParseInboundEmailWebhook(Stream stream) in C:\projects\stronggrid\Source\StrongGrid\WebhookParser.cs:line 116
   at Webhooks_Test.can_read_file() in C:\Test\UAC_Webhooks_Test.cs:line 24
Result Message:	
Test method UAC_Webhooks_Test.can_read_file threw exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
```
Any ideas what's going on?

**Comment by smillerk2** [comment] 2017-10-26 14:11
My package version was 0.29. I have updated to 0.31 and the test passes now.

**Comment by Jericho** [comment] 2017-10-26 14:27
The `index out of range` exception was an [issue](#197) that was resolved in release 0.30.0

**Closed** 2017-10-27 17:38 UTC
Labels: question

**Comment by smillerk2** [comment] 2017-11-07 03:06
Do you have a unit test example that covers both raw and default parsed emails from SendGrid? Having some issues with boundary exceptions but not sure if that's their bad examples or line breaks.

**Comment by Jericho** [comment] 2017-11-07 03:53
The inbound email parser in StrongGrid does not work when data posted from SendGrid is in "raw" format (see discussion in #176), so I don't have an example for that. As far as the "default" format, I did write a unit test based following the discussion you and I had in this issue but I just realized that I saved it in the wrong location. Anyway... I moved the unit test to its proper location and you can see it [here](https://github.com/Jericho/StrongGrid/blob/develop/Source/StrongGrid.UnitTests/WebhookParserTests.cs#L357).

**Comment by pllamena** [comment] 2020-10-03 18:13
Hello @Jericho,
I know this issue is old and closed, but I wasn't sure if I should open a new one for the same error.  I am getting the same [MultipartParseException]: Duplicate field in section Exception with the default Send Grid payload ( https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/#example-default-payload ). Currently for testing I am reading it from a .txt file like in your unit test above.

**Comment by Jericho** [comment] 2020-10-03 18:28
I suggest you go ahead and raise a new issue and make sure you post enough information to help me reproduce the problem you are experiencing. For instance, include a copy of the txt file, any c# code snipet you are using, etc. Without this kind of info I will not be able to help.

Also, and **THIS IS CRITICAL**: check, double-check and triple-check that you didn't configured SendGrid to send you the "raw" format. In other words, make sure the "POST the raw, full MIME message" setting is **NOT** checked like in this example:

![image](https://user-images.githubusercontent.com/112710/94999055-829bc280-0584-11eb-8446-e5ae2f3439fa.png)
