### ISSUE TITLE
"Duplicate field in section" MultipartParseException in Email Parse

### ISSUE THREAD

**Issue by pllamena** [Jericho/StrongGrid#346] opened 2020-10-04 02:09 UTC
Hi @Jericho , 

Thank you for the quick response! I am opening a new issue similar to #202 

I am trying to parse the example default payload for inbound email (https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/#example-default-payload).  I have it saved as a txt file (attached below), opening it with:

`using (var stream = System.IO.File.OpenRead(path))  {
    var parser = new StrongGrid.WebhookParser();
    var inboundEmail = parser.ParseInboundEmailWebhook(stream); ...`

The ParseInboundEmailWebhook method throws a "Duplicate field in section" MultipartParseException:
![image](https://user-images.githubusercontent.com/30033716/95005355-49d00d80-05c5-11eb-8182-ccac0071dbd0.png)

Please let me know if I can provide any more details!  I triple checked that SendGrid is NOT configured to send the raw format, although I am not sure that matters when working with the default example.

[InboundEmail.txt](https://github.com/Jericho/StrongGrid/files/5322564/InboundEmail.txt)

Thank you!

**Comment by Jericho** [comment] 2020-10-04 02:20
I just realized that you are using SendGrid's sample payload. That's the cause of the problem you are experiencing. In fact, it was mentioned in the issue you referenced, in addition to at least one other issue (see discussion in #176). 

The inbound email parser in StrongGrid does not work when data posted from SendGrid is in "raw" format and the sample payload provided by SendGrid is in the format we do not support.

**Comment by pllamena** [comment] 2020-10-04 02:44
Are both samples provided by SendGrid 'raw'?  There are two examples in their documentation and I could be wrong, but I thought the first one is **not** 'raw'.

**Comment by Jericho** [comment] 2020-10-04 02:51
I have only witnessed the “Duplicate field in section” exception when attempting to parse a webhook payload in raw format, and I know SendGrid’s sample payload is in raw format. That’s why I concluded that you must be using a sample in raw format.

Why not use the sample I provided back in 2017 (https://github.com/Jericho/StrongGrid/issues/202#issuecomment-339667513) or, better yet, get an actual payload posted by SendGrid to you.

**Comment by pllamena** [comment] 2020-10-04 03:02
Good point, I was focused on the implementation of processing the inbound emails, let me try an actual payload on Monday and I will close the issue if that works.

**Comment by Jericho** [comment] 2020-10-04 03:03
Sounds good.

**Comment by Jericho** [comment] 2020-11-05 20:02
@pllamena I'm assuming you were able to get this to work therefore I will go ahead and close this issue. Let me klow if that's not the case and I'll be glad to reopen.

**Comment by pllamena** [comment] 2020-11-08 17:12
Hi @Jericho , I actually still haven't had a chance to test with a real payload.  We run into issues with the dns config where the inbound is not coming through and have been working with SendGrid's support to figure that out, but the actual parser exception is still not resolved on my end.

**Comment by Jericho** [comment] 2020-11-08 18:27
While you sort out your DNS issue, have you tried the sample I provided?

**Comment by pllamena** [comment] 2020-11-08 18:55
Yes, that sample worked!

**Closed** 2020-11-22 18:20 UTC
