### ISSUE TITLE
MailAddress.Name must be quoted when containing a comma

### ISSUE THREAD

**Issue by spib** [Jericho/StrongGrid#189] opened 2017-09-12 08:44 UTC
Hi,

I ran into a weird issue today whereby emails sent with StrongGrid were getting corrupted. Sending to a recipient with the email address 'john@test.com' would end up in SendGrid as 'john' (no domain name) and would therefore be dropped.

After working through it with SendGrid support, we discovered that it was because the name I was adding for this recipient contained a comma (e.g. 'John H. Smith, HMCC' , which apparantly is not allowed (see the to->name parameter on this page https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html).

The solution is to either remove the comma/semi-colon or to URL encode the value.

I wondered what we could do within StrongGrid to fix this? Would it perhaps make sense to throw an exception in the MailAddress class if you add a name containing these disallowed characters? Or maybe have StrongGrid url-encode the parameter instead?

Interested to know your thoughts, thanks again for a great library

James

**Comment by Jericho** [comment] 2017-09-12 15:09
It's ironic that SendGrid says recipients name cannot include a comma when sending emails because there's a [recently reported issue](https://github.com/Jericho/StrongGrid/issues/185) in StrongGrid's webhook parser that is caused by names containing commas when SendGrid sends a webhook.

They told you that, as a workaround, it was acceptable to URL encode the recipients name? That's very interesting. I didn't see that recommendation in the mail API document though. Nonetheless, URL encoding names sounds like a much more reasonable approach than completely disallowing commas.

I use Json.net to convert objects (such as MailAdress) into Json to be sent to SendGrid. Let me investigate if there's a way to configure Json.net to url encode certain fields and, if so, I'll be happy to update StrongGrid to automatically encode recipients name.

**Comment by spib** [comment] 2017-09-12 15:46
Yeah, their recommendation to URL encode came direct from their support team

> To resolve this issue you'll need to either remove the , from the To: name, or you'll need to URL encode it.

Agreed that url encoding would be cleaner

**Comment by Jericho** [comment] 2017-09-14 22:05
Can you confirm with their support team that they want a name like `Smith, Bob` to be encoded like so: `Smith%2C%20Bob`?

**Comment by Jericho** [comment] 2017-09-14 22:34
Interestingly, SendGrid seems to support commas in the "from" name without the need for any encoding:

![image](https://user-images.githubusercontent.com/112710/30458805-3999bd3a-997b-11e7-943d-8df7f91b7d02.png)

**Comment by spib** [comment] 2017-09-15 17:27
Here's the response I got from SendGrid

> One way you can accomplish this if you need to continue using commas is to put the to name in quotes like this:
> 
>     "name":"\"Last, First\""
> 
> It will show those quotes on the to address but it will allow the use of a comma.

**Comment by Jericho** [comment] 2017-09-15 21:03
So they are backtracking on the recommendation to URL encode the names?

**Comment by Jericho** [comment] 2017-09-15 21:22
I confirm that surrounding the recipient's name with double quote like this example: `"\"Smith, Bob\""` results in the email being successfully sent and it looks fine when viewed in Outlook. In fact, contrary to what they told you, the double quotes do not show:

![image](https://user-images.githubusercontent.com/112710/30503899-0e008310-9a3a-11e7-8b33-ae0c24b8dae2.png)

**Comment by Jericho** [comment] 2017-09-16 22:10
This is being released in 0.29.0

**Closed by Jericho** 2017-09-16 22:10 UTC
Labels: New Feature
