### ISSUE TITLE
The WebhookParser does not parse attachments

### ISSUE THREAD

**Issue by fiatkongen** [Jericho/StrongGrid#304] opened 2019-12-03 17:22 UTC
The WebhookParser does not seem to parse attachments. The unit tests parsing the example file "raw_data_with_attachments" does not return any attachments. Is this a bug?

**Comment by Jericho** [comment] 2019-12-04 17:56
The unit test parsing the `raw_data_with_attachments` file is intended to test the scenario where you have configured Sendgrid to send you the "raw" message which is NOT how you would typically configure your "Inbound Parse".

![image](https://user-images.githubusercontent.com/112710/70167087-fda9f900-1693-11ea-88ba-3fe60048a7e6.png)

In this configuration, the raw message is not parsable which means that StrongGrid can't parse attachments.

All this to say that if you want StrongGrid to be able to parse attachments, you must NOT configure you SendGrid inbound parse to only send the raw message.

**Comment by fiatkongen** [comment] 2019-12-04 21:19
Thanks for clarifying that :-) And thank you for a great library, that really fills a blank spot.

My Sendgrid is configured as you suggest, but I no matter what, when I recieve an email with an attachment I end up with an
**Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException** whenever calling the **ParseInboundEmailWebhookAsync**. Do you have a clue for where to look for the problem I am facing?

**Comment by Jericho** [comment] 2019-12-04 22:09
Its really hard for me to guess what might be the problem without more details. Are you able to share the stack trace of this error? Even better: can you write the content of the web hook to a text file and post it here? That would potentially allow me to reproduce the problem.

**Comment by fiatkongen** [comment] 2019-12-05 12:31
Thanks. I will do that :-)

**Comment by Jericho** [comment] 2019-12-10 15:06
**Update**: I have renamed the file `raw_data_with_attachments` to `raw_data` to avoid confusion in the future.

**Comment by Jericho** [comment] 2019-12-12 16:46
@fiatkongen Do you have any additional information about this issue? Do you still need help investigating?

**Comment by Jericho** [comment] 2019-12-16 13:41
I'm going to close this case but feel free to reopen it if you can provide additional information.

**Closed by Jericho** 2019-12-16 13:41 UTC
Labels: question
