### ISSUE TITLE
Support Email Validation API

### ISSUE THREAD

**Issue by spib** [Jericho/StrongGrid#297] opened 2019-08-07 13:47 UTC
Hi,

Do you plan to support the new Email Validation API?

https://sendgrid-email-validation.api-docs.io/v3/validate-an-email/validate-an-email

**Comment by Jericho** [comment] 2019-08-07 14:13
Sure I do but not until I gain access to this new functionality otherwise I won't be able to test. As I understand it, it's currently in beta and only a select few have access to it.

**Comment by Jericho** [comment] 2019-12-11 16:08
Quick update: I haven't been able to access this functionality so, unfortunately, can't test. 

@spib If I publish a beta package to my MyGet feed, would you be able to test it and report back if it works or encounter any issue?

**Comment by hostr** [comment] 2019-12-13 19:27
I'd be happy to work with on this with you @Jericho. I'm able to create an API key [here](https://app.sendgrid.com/settings/api_keys). It's a completely separate permission called Email Address Validation Access.

I see your start on it in feature/email_validation, but that won't work because the response doesn't match their current result. https://github.com/Jericho/StrongGrid/blob/cefe1b2a33e8c69e893d72b4d7c1f0a2f58e4812/Source/StrongGrid/Models/EmailValidationResult.cs should match the [documented schema](https://sendgrid-email-validation.api-docs.io/v3/validate-an-email/validate-an-email). I have tested and these docs are now up to date.

**Comment by Jericho** [comment] 2019-12-13 21:08
It didn't occur to me that SendGrid had created a new permission for address validation (doesn't seem to be documented either). I can grant this new permission to my api key and I will be able to progress.

I'm sure SendGrid made changes to the schema since last time I worked on this feature, that would explain why my model doesn't match their schema but I will rectify and publish a beta package to my MyGet feed shortly. I'll let you know when it's ready for testing.

Thanks agin for the info.

**Comment by Jericho** [comment] 2019-12-13 21:49
Unfortunately, I can't grant 'Email Address Validation' to my API keys:

![image](https://user-images.githubusercontent.com/112710/70833569-2766cc80-1dc6-11ea-9b94-f413a47a8f5e.png)

I guess I haven't been granted access to this new feature (which, as far as I know, is still in beta). So, I'll have to rely on you @hostr to test my work.

**Comment by hostr** [comment] 2019-12-13 22:04
@Jericho according to the tip [here](https://sendgrid.com/docs/ui/managing-contacts/email-address-validation/) it's only available for Pro or Premier accounts.

> “Email Address Validation Access” will be visible to Email API Pro and Premier plans only.

It is in the [official v3 docs](https://sendgrid.api-docs.io/v3.0/email-address-validation/validate-an-email) now so I'm guessing it's out of beta, but I don't have any production experience with it yet either.

**Comment by Jericho** [comment] 2019-12-13 22:48
Here's an [alpha version](https://www.myget.org/feed/jericho/package/nuget/StrongGrid/0.63.0-alpha0036) for you to test with.

If you could, can you capture a response from SendGrid when invoking `EmailValidation.ValidateAsync` and post it here? This will help me write unit tests.

**Comment by Jericho** [comment] 2019-12-20 18:42
Another [alpha release](https://myget.org/feed/jericho/package/nuget/StrongGrid) with fixes and improvements based on information from https://sendgrid.com/docs/ui/managing-contacts/email-address-validation/

**Comment by Jericho** [comment] 2019-12-28 00:48
@spib @hostr Did you have a chance to look at the alpha release I published?

**Comment by hostr** [comment] 2020-01-02 17:15
Hey @Jericho, sorry for the delay, I've been pretty off the grid during the holidays. I tested it out and it looks like most of it is good (successful responses are mapping correct, 401's and 403's). One issue is that the source is not required in the request so this should an optional arg. I created PR #309 to fix this.

Here's an example in json:

**Request**
```json
{
	"email": "ajskdlfj@ajsdklf.co"
}
```

**Response**
```json
{
    "result": {
        "email": "ajskdlfj@ajsdklf.co",
        "verdict": "Invalid",
        "score": 0,
        "local": "ajskdlfj",
        "host": "ajsdklf.co",
        "checks": {
            "domain": {
                "has_valid_address_syntax": true,
                "has_mx_or_a_record": false,
                "is_suspected_disposable_address": false
            },
            "local_part": {
                "is_suspected_role_address": false
            },
            "additional": {
                "has_known_bounces": false,
                "has_suspected_bounces": false
            }
        },
        "ip_address": "123.123.123.123"
    }
}
```

Here's another request for your tests with source included.
**Request**
```json
{
	"email": "samoway973@mtsg.me",
	"source": "test"
}
```

**Response**
```json
{
    "result": {
        "email": "samoway973@mtsg.me",
        "verdict": "Valid",
        "score": 0.93357,
        "local": "samoway973",
        "host": "mtsg.me",
        "checks": {
            "domain": {
                "has_valid_address_syntax": true,
                "has_mx_or_a_record": true,
                "is_suspected_disposable_address": false
            },
            "local_part": {
                "is_suspected_role_address": false
            },
            "additional": {
                "has_known_bounces": false,
                "has_suspected_bounces": false
            }
        },
        "source": "TEST",
        "ip_address": "123.123.123.123"
    }
}
```

I wasn't able to get a `suggestion` back with the JSON response, but it ends up as null in the response object so that should be fine.

**Comment by Jericho** [comment] 2020-01-02 18:13
Excellent! Thanks for the feedback. I merged your PR and will probably write a few more unit tests based on the json you captured.

I will work on this shortly and publish next release as soon as I can.

**Comment by Jericho** [comment] 2020-01-02 22:29
@hostr Regarding your PR: I checked SendGrid's documention and I confirmed that `source` is indeed optional but I also discovered that `email` is also indicated as being optional:
![image](https://user-images.githubusercontent.com/112710/71696834-0c172d80-2d84-11ea-8eea-bc300edccd2b.png)

How can you validate an email address if an email address is not provided!?!?!?!?

I'm guessing that's a typo. What do you think?

**Comment by hostr** [comment] 2020-01-02 22:47
Haha yes, I saw that earlier too and had to test. It is definitely a typo. When I attempted it gave me an error saying email address is required.

**Closed** 2020-01-03 01:35 UTC
Labels: New Feature

**Comment by Jericho** [comment] 2020-01-03 03:13
Latest packaged pushed to Nuget with this new functionality.

Thank you @spib for suggesting it and thank you @hostr for testing it.
